#!/bin/ksh

if [ $(id -u) -ne 0 ]
then
  echo "Run as root."
  exit
fi

if [[ $# -eq 0 ]]
then
  echo "usage: new_httpd_website [name]"
  exit
fi

NAME=$1

if getent passwd $NAME >> /dev/null
then
  echo "'$NAME' already exists. Try a different name."
  exit
fi

useradd -mv -b /home/$NAME -d /home/$NAME $NAME
git init --bare /home/$NAME/$NAME.git

echo "\
#!/bin/sh\n\
\n\
TARGET=/var/www/htdocs/$NAME\n\
TEMP=/home/$NAME/temp\/\n\
\n\
mkdir -p \$TEMP\n\
git --work-tree=\$TEMP checkout -f\n\
\n\
rsync -av \$TEMP \$TARGET\n\
rm -rf \$TEMP\n\
" > /home/$NAME/$NAME.git/hooks/post-receive
chmod +x /home/$NAME/$NAME.git/hooks/post-receive

chown -R $NAME /home/$NAME/*
mkdir /var/www/htdocs/$NAME
chown -R $NAME /var/www/htdocs/$NAME
