#!/bin/ksh

if [ $(id -u) -ne 0 ]
then
  echo "Run as root."
  exit
fi

if [[ $# -eq 0 ]]
then
  echo "usage: new_httpd_website [name]"
  exit
fi

NAME=$1

if getent passwd $NAME >> /dev/null
then
  echo "'$NAME' already exists. Try a different name."
  exit
fi

useradd -mv -b /home/$NAME -d /home/$NAME $NAME
mkdir /var/www/htdocs/$NAME
chown -R $NAME /var/www/htdocs/$NAME
